# Generated by Django 4.2.11 on 2024-04-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0003_custombakeryorder_delivery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custombakeryorder',
            old_name='price',
            new_name='total_price',
        ),
    ]
