# Generated by Django 4.2.11 on 2024-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0004_rename_price_custombakeryorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombakeryorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
